server:
  port: 8001
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: service-knowledge
  #  数据库配置
  datasource:
    username: root
    password: 2003
    url: jdbc:mysql://localhost:3306/monsoon_knowledge?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml


